- iexfinance/__init__.py
> Updated maximum symbol list length

- tests/tests.py
> Updated test for symbol list length

- README.rst
v0.2.0 is experiencing issues due to #23 . Recommend use development version until v0.3.0 released.
> DOCS: Add warning to README for current issues

- iexfinance/__init__.py
> Update version for rls 0.3.2

- iexfinance/__init__.py
The IEX API allows for calls of up to (including) 100 symbols.
> Update size restriction for calls

- docs/source/stocks.rst
- docs/source/whatsnew.rst
- docs/source/whatsnew/v0.3.5.txt
- iexfinance/__init__.py
- tests/test_stock.py
Implemented `stock/market/sector-performance` endpoint.
For more info see https://iextrading.com/developer/docs/#sector-performance
> Added sector-performance endpoint

- docs/source/stocks.rst
- docs/source/whatsnew/v0.3.5.txt
- iexfinance/__init__.py
- iexfinance/stock.py
- tests/test_stock.py
I've added test and docs entry. Hope we can squeeze in this changeset into 0.35 :)
> Added top 10 infocus list endpoint 

- iexfinance/base.py
- iexfinance/market.py
- iexfinance/ref.py
- iexfinance/stats.py
- iexfinance/stock.py
- iexfinance/utils/__init__.py
- tests/test_market.py
- tests/test_stock.py
- tests/test_utils.py
> CLN: Repair docstrings. Add proper list handling

- .travis.yml
- MANIFEST.in
- docs/source/caching.rst
- docs/source/market.rst
- docs/source/stocks.rst
- docs/source/usage.rst
- requirements-dev.txt
- requirements-test.txt
- setup.cfg
- setup.py
- test.sh
Added ``flake8-rst`` requirement to CI and ``test.sh`` script.
> Add docs code block linting

- docs/source/whatsnew.rst
- docs/source/whatsnew/v0.3.6.txt
- iexfinance/stocks/historical.py
- tests/test_stocks.py
> BUG: Repair Intraday date formatting

- .travis.yml
- README.rst
- docs/source/account.rst
- docs/source/configuration.rst
- docs/source/testing.rst
- docs/source/usage.rst
- iexfinance/base.py
- iexfinance/stocks/historical.py
- iexfinance/tests/fixtures.py
- iexfinance/tests/test_base.py
- iexfinance/tests/test_cloud_migration.py
- iexfinance/tests/test_iexdata.py
> DOC/TST: Update docs, pass v1 tests

- docs/source/testing.rst
- docs/source/whatsnew/v0.4.1.txt
- iexfinance/base.py
- iexfinance/utils/__init__.py
Adds client support for IEX Cloud [sandbox environment](https://iexcloud.io/docs/api/#sandbox)
Access available using test tokens and setting ``IEX_API_VERSION`` to ``iexcloud-sandbox``.
*Note: test suite will be converted to use sandbox environment in near future for proper testing and CI*
> Sandbox env

- docs/source/whatsnew.rst
- docs/source/whatsnew/v0.4.1.txt
- iexfinance/base.py
- iexfinance/stocks/base.py
- iexfinance/tests/test_stocks.py
- iexfinance/utils/testing.py
> BUG: Repair output formatting for financial statements & estimates

- README.rst
- docs/source/configuration.rst
- docs/source/index.rst
- docs/source/whatsnew/v0.4.2.txt
- iexfinance/account/base.py
- iexfinance/altdata/base.py
- iexfinance/apidata/base.py
- iexfinance/base.py
- iexfinance/refdata/base.py
- iexfinance/stocks/base.py
- iexfinance/stocks/marketvolume.py
- iexfinance/tests/stocks/test_endpoints.py
- iexfinance/utils/__init__.py
- iexfinance/utils/exceptions.py
> DEPR: End support for IEX Version 1 Developer API (legacy)

- docs/source/conf.py
- iexfinance/base.py
- iexfinance/stocks/historical.py
- iexfinance/tests/stocks/test_endpoints.py
- iexfinance/tests/stocks/test_formats.py
> CLN: Clean tests & signatures for 0.4.2

- docs/source/whatsnew/v0.4.3.txt
- iexfinance/tests/stocks/test_endpoints.py
- iexfinance/tests/test_altdata.py
> TST/DOC: Prepare for 0.4.3 release

- iexfinance/base.py
- iexfinance/utils/exceptions.py
* Make error message for IEXQueryError reflect API error
* Print status code and text of response
Alternative to https://github.com/addisonlynch/iexfinance/pull/180
> Add status code and response text to error message

- iexfinance/account/__init__.py
- iexfinance/account/base.py
- iexfinance/altdata/__init__.py
- iexfinance/altdata/base.py
- iexfinance/apidata/__init__.py
- iexfinance/data_apis/__init__.py
- iexfinance/data_apis/data_points.py
- iexfinance/data_apis/time_series.py
- iexfinance/iexdata/__init__.py
- iexfinance/iexdata/base.py
- iexfinance/stocks/base.py
> STY: Repair docstrings & clean code

- iexfinance/stocks/historical.py
- iexfinance/tests/data_apis/test_time_series.py
- iexfinance/tests/fixtures.py
- iexfinance/tests/stocks/test_formats.py
* Repair broken tests
* Repair ``chart_range`` handling in ``HistoricalReader``
> Repair tests

- docs/source/refdata.rst
- docs/source/whatsnew/v0.5.0.txt
- iexfinance/iexdata/__init__.py
- iexfinance/refdata/__init__.py
- iexfinance/refdata/base.py
- iexfinance/stocks/base.py
- iexfinance/stocks/historical.py
- iexfinance/tests/data_apis/test_time_series.py
- iexfinance/tests/fixtures.py
- iexfinance/tests/stocks/test_formats.py
- iexfinance/tests/test_refdata.py
* I think it did at least. It didn't print anything so I assume that's a pass
> Add trading days/holidays endpoint to refdata

- docs/source/conf.py
- docs/source/refdata.rst
- docs/source/whatsnew/v0.5.0.txt
- docs/source/whatsnew/vLATEST.txt
- iexfinance/refdata/__init__.py
- iexfinance/refdata/base.py
- iexfinance/tests/test_refdata.py
Accessible via new get_sectors method within ref_data module
Added tests and doc entry. 
Not sure what is the black iexfinance` and the git upstream
> Add Sectors endpoint. 

- docs/source/whatsnew.rst
- docs/source/whatsnew/v0.5.1.txt
- iexfinance/stocks/base.py
- iexfinance/stocks/historical.py
> BUG: Re-add dropped date column 

- docs/source/about.rst
- docs/source/caching.rst
- docs/source/conf.py
- docs/source/configuration.rst
- docs/source/iexdata.rst
- docs/source/index.rst
- docs/source/market-info.rst
- docs/source/sandbox.rst
- docs/source/stocks.rst
- docs/source/testing.rst
- docs/source/usage.rst
- docs/source/whatsnew/v0.4.1.txt
- docs/source/whatsnew/v0.5.0.txt
- docs/source/whatsnew/v0.5.1.txt
> DOC: Repair broken links

- docs/source/crypto.rst
- docs/source/whatsnew/v0.5.1.txt
- iexfinance/altdata/__init__.py
- iexfinance/crypto/__init__.py
- iexfinance/crypto/base.py
- iexfinance/tests/test_altdata.py
- iexfinance/tests/test_crypto.py
* Moves cryptocurrency quotes from ``iexfinance.altdata`` to new module ``iexfinance.crypto``
* Adds ``get_crypto_book`` and ``get_crypto_price``
> ENH: Updates to cryptocurrencies
