iexfinance/iexretriever.py
Fixes #2 
**Default options**
Ensured that the chart parameter would be passed ahead of the others. See iexg/IEX-API#156, as this seems to be a temporary workaround (will need to repair once they fix on their end)
**Non-default options**
Endpoints that returned empty from the query (i.e. a company with no recent splits such as AAPL) were not updating themselves in the dataset. For those endpoints we added code which manually inserts an empty list for those endpoints.
=> Repaired default and nondefault options

iexfinance/iexretriever.py
This forces the chart endpoint to the beginning of the URL so it will download correctly until the IEX API bug is repaired by the provider.
=> Further temporary corrections to chart endpoint

.travis.yml, iexfinance/market.py, iexfinance/stats.py, setup.py
Repairs compatibility discrepancies between pypi and travis 
* Removes listed support for python 2.6, 3.3
* Adds 3.4, 3.6, 2.7 support to TravisCI
Fixes #18
=> COMPAT: Python versions

docs/source/ref.rst, docs/source/stocks.rst, docs/source/usage.rst, iexfinance/__init__.py, iexfinance/base.py, iexfinance/stock.py, tests/test_stock.py
Fixes #15, #23, #24, #25, #27, #28. 
- Stock endpoint requests are now made on a per-call basis. All endpoints are not downloaded at instantiation.
- ``refresh`` has been removed
- ``get_select_endpoints`` is now ``get_endpoints``
- ``get_select_datapoints`` has been removed
- Parameters to individual endpoints (such as ``displayPercent`` for Quote) are now passed to the endpoint methods as keyword arguments, rather than the Stock method at instantiation:
```python
from iexfinance import Stock
aapl = Stock("AAPL")
aapl.get_quote(displayPercent=True)
```
- Field methods have been rebuilt. Now support DataFrame output formatting.
- Cleans docs for RLS 0.3.0
=> Stocks refactor

docs/source/whatsnew/v0.4.0.txt, iexfinance/stock.py, tests/test_stock.py
=> Repair earnings and financials indexing

docs/source/whatsnew/v0.3.1.txt, iexfinance/base.py
=> Repairs request mechanism for non-alphanum tickers

docs/source/whatsnew.rst, docs/source/whatsnew/v0.3.2.txt, iexfinance/market.py, tests/test_market.py, tests/test_stock.py
* Repairs IEX Market Data Filtering (fixes #46)
* Repairs Stocks endpoint tests (fixes #45)
=> Repair IEX Market Data filtering, Stock endpoint tests

docs/source/conf.py, iexfinance/base.py, iexfinance/stats.py, tests/test_stock.py
Allow correct financial calculation using the Decimal data type by letting the JSON parser turn float-like values into Decimal.
This behaviour can be specified during class creation using the kwarg 'json_parse_int' and 'json_parse_float' to parse INTs and FLOATs into Decimal respectivelly.
Example:
from decimal import Decimal    
Stock('aapl', 
json_parse_int=Decimal, 
json_parse_float=Decimal
).get_dividends(range='1y')
=> Financial decimal parsing

docs/source/whatsnew/v0.3.4.txt, iexfinance/stock.py, tests/test_stock.py
Deliver an empty list to denote the missing iterable data.
=> Fix KeyError exception when there is no earnings or financials data on a ticker.

docs/source/whatsnew/v0.3.3.txt, docs/source/whatsnew/v0.3.4.txt, iexfinance/stock.py, tests/test_stock.py
- Deliver an empty list to denote the missing iterable data for symbols without earnings or financials (thank you @reixd)
- Change historical test cases ticker from AAPL to AMZN to avoid issues with adjusted prices (AMZN does not normally declare dividends, whereas Apple does. This may have caused some test cases to fail)
=> Repair exceptions and test cases 

iexfinance/iexdata/__init__.py, iexfinance/stocks/base.py, iexfinance/tests/test_stocks.py, requirements-dev.txt
https://travis-ci.com/gliptak/iexfinance/builds/107558252
```3.4``` fails with ```ERROR: Sphinx requires at least Python 3.5 to run.```
Others fail on earnings unit tests.
=> Correct Travis build (setting pytest>=4)

iexfinance/tests/stocks/test_endpoints.py, iexfinance/tests/test_altdata.py
* ``get_crypto_quotes`` - provider returns 18 fields instead of 44
* Removed end of day checks from ``get_historical_intraday`` which caused tests to fail during market hours
=> TST: Repair failing tests with new field counts from provider

iexfinance/tests/stocks/test_endpoints.py, iexfinance/tests/stocks/test_formats.py
Uses ``pandas.api.is_number`` to check numerical values returned. This should repair many issues where ``int``s are returned for precise values
=> TST: Allow all numerical types in numerical value checks

README.rst, docs/source/stocks.rst, docs/source/whatsnew.rst, docs/source/whatsnew/v0.4.2.txt, iexfinance/stocks/__init__.py, iexfinance/stocks/historical.py, iexfinance/tests/stocks/test_endpoints.py, iexfinance/utils/__init__.py
As noted by @shlomikushchi in #148, ``HistoricalReader`` is not currently optimized for single day requests and for retrieving close only.
* Add ``close_only`` parameter to ``get_historical_data`` to allow retrieval of close prices only to reduce message count (through ``chartCloseOnly``)
* Optimize single-day requests to ``get_historical_data`` such that they use ``date`` as a range and set ``chartByDay`` to ``True``
Clarifies documentation to specify ``get_historical_data`` as *optimized* and accepting a date range and ``close_only`` as parameters, while ``Stock.get_historical_prices`` is an exact mirror of the Historical Prices endpoint which accepts any parameter from the IEX docs
=> PERF: Optimize Stocks get_historical_data to reduce message count in queries

README.rst, docs/source/index.rst, docs/source/options.rst, docs/source/stocks.rst, docs/source/whatsnew/v0.4.2.txt, iexfinance/stocks/__init__.py, iexfinance/stocks/options.py, iexfinance/tests/stocks/test_endpoints.py
Add support for [End of Day Options](https://iexcloud.io/docs/api/#end-of-day-options)
=> ENH: Add support for End of Day Options

docs/source/whatsnew/v0.4.4.txt, iexfinance/stocks/base.py
``Stock.get_historical_prices`` and ``Stock.get_chart`` were truncated to only return ``Open``, ``High``, ``Low``, and ``Close`` fields. These have been modified to now return all fields (see below)
=> BUG: Return all fields from Stock.get_historical_prices and Stock.get_chart

docs/source/stocks.rst, docs/source/whatsnew/v0.4.4.txt, iexfinance/stocks/historical.py, iexfinance/tests/stocks/test_endpoints.py
=> ENH/BUG: Optimize historical message weighting, allow 15 years of data

docs/source/whatsnew/v0.5.0.txt, iexfinance/iexdata/__init__.py, iexfinance/iexdata/base.py, iexfinance/stocks/__init__.py, iexfinance/stocks/historical.py, iexfinance/tests/test_iexdata.py, iexfinance/tests/test_utils.py, iexfinance/utils/__init__.py
Repairs all date handling
* Use rolling 15 year default start date
* Accept multiple formats, including ``int``, ``str``, ``date``, ``datetime``, and ``pandas.Timestamp``
=> ENH/BUG: Repair date handling

iexfinance/stocks/base.py
Added more specific error message. As currently is, took me coming to the source code to debug the original error message.
=> Explicit error handling for incorrect number of Stock symbols

docs/source/stocks.rst, docs/source/whatsnew/v0.5.0.txt, iexfinance/stocks/base.py, iexfinance/tests/stocks/test_endpoints.py, iexfinance/tests/stocks/test_formats.py, setup.cfg
* Ignored common library files from flake8 configuration.
* Fixed test that wouldn't pass unrelated to change in: test_get_dividends_params.
* Updated documentation.
- [x ] tests added / passed
- [ x] passes `black iexfinance`
=> [Stocks] Added Advanced Stats Endpoint.

.travis.yml, docs/source/conf.py, docs/source/market-info.rst, docs/source/stocks.rst, docs/source/usage.rst, docs/source/whatsnew/v0.5.0.txt, iexfinance/base.py, iexfinance/stocks/base.py, iexfinance/tests/stocks/test_field_methods.py, iexfinance/tests/stocks/test_fundamentals.py, iexfinance/tests/stocks/test_ipo_calendar.py, iexfinance/tests/stocks/test_research.py, iexfinance/utils/__init__.py, setup.cfg
- Fundamentals only return 3 periods max. IEX Bug. xfail tests for now
- Price Target requires special access
- IPO Calendar endpoint temporarily disabled
- iexfinance bug: Incorrect return statement messed up output formatting for historical prices
Other maintenance items:
* Remove python 3.4 from travis
* Repair bug for pandas < 1.0 where incompatible types were compared in ``_utils._sanitize_dates``
* Repair compatibility issues between ``flake8`` and ``black``
=> BUG/TST: Repair failing tests and restore CI

docs/source/data-apis.rst, docs/source/refdata.rst, docs/source/whatsnew/v0.5.0.txt, iexfinance/refdata/__init__.py, iexfinance/refdata/base.py, iexfinance/tests/test_refdata.py
Adds support for these endpoints: https://iexcloud.io/docs/api/#international-symbols
This PR also includes some cleanup requested by `black iexfinance`.
=> ENH: Support reference data international symbols endpoints

docs/source/stocks.rst, docs/source/testing.rst, iexfinance/base.py, iexfinance/tests/conftest.py, iexfinance/tests/data_apis/test_time_series.py, iexfinance/tests/stocks/test_market_movers.py, iexfinance/tests/test_iexdata.py, test.sh
- Remove `xfail` decorators from tests that passed.
- Add a couple instructions and details to `test.sh`
script on token usage and potential failures
- Automatically change to sandbox environment if
IEX token starts with 'Tsk' or 'Tpk'.
Pytests:
```
======================================================== test session starts =========================================================
platform darwin -- Python 3.7.7, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/olshansky/workspace/iexfinance, configfile: pytest.ini
collected 168 items
iexfinance/tests/test_account.py ssssssss                                                                                      [  4%]
iexfinance/tests/test_altdata.py ...sssss.. …
```
=> CLN/TST: Cleanup some tests.
